name: ${name}
main: fr.areku.minecraft.sec.SecurityPlugin
author: ThisIsAreku
website: http://areku.fr/
version: ${version}
description: Various security fix
softdepend: [PermissionsEx]
depend: [plugins-common]
commands:
  l:
    description: Login yourself
    aliases: login
  normal:
    description: Reset yourself
  server-lock:
    description: lock the server